# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8146428adc3dda8b91c6518ccc27167699da664aa225816acdcc8317a482b8c73a9e3c6a7bc4beaf7f211cb966951e768cc2d0e6d6029411c81c5b386004ece

test:
  secret_key_base: 7fe1963c1dcc46e19168a4a6c9400cc8d151c42dc8129df3574b1af799018b79d01f3b97a3f3c9a4dba600bfb8f89b1cac2cd31c707632b1413fa6551e92cbe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
